-- ===========================================================================
-- Rechnungsmodul – aus dem alten Manus-Rechnungsprogramm übernommen.
-- Ein Nutzer, RLS aktiv (gleiches Muster wie Bestandsschema).
-- Beträge als ganze Cent (bigint). IDs als bigint identity, beim Import werden
-- die alten IDs 1:1 übernommen (FK-Beziehungen bleiben erhalten); die Sequenz
-- wird danach hochgesetzt. Enums als text + CHECK (lazy, wie categories→text).
-- ===========================================================================

create table companies (
  id bigint generated by default as identity primary key,
  name text not null,
  street text,
  zip_code text,
  city text,
  phone text,
  email text,
  website text,
  tax_number text,
  vat_id text,
  iban text,
  bic text,
  bank_name text,
  owner text,
  first_name text,
  last_name text,
  logo_url text,
  invoice_prefix text not null default 'RE',
  invoice_counter int not null default 0,
  invoice_intro_text text,
  invoice_footer_text text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table customers (
  id bigint generated by default as identity primary key,
  customer_number text not null unique,
  company_name text,
  first_name text,
  last_name text,
  street text,
  zip_code text,
  city text,
  country text default 'Deutschland',
  tax_region text not null default 'inland'
    check (tax_region in ('inland', 'eu', 'drittland')),
  email text,
  phone text,
  tax_id text,
  notes text,
  company_id bigint references companies(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  customer_id bigint not null references customers(id),
  invoice_date timestamptz not null,
  service_start_date timestamptz,
  service_end_date timestamptz,
  due_date timestamptz not null,
  payment_term_days int not null default 7,
  status text not null default 'draft'
    check (status in ('draft', 'open', 'paid', 'overdue', 'cancelled')),
  vat_rate int not null default 19,
  is_reverse_charge boolean not null default false,
  subtotal bigint not null,
  vat_amount bigint not null,
  total bigint not null,
  paid_amount bigint not null default 0,
  paid_date timestamptz,
  notes text,
  pdf_url text,
  company_id bigint references companies(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references invoices(id) on delete cascade,
  position int not null,
  description text not null,
  details text,
  quantity numeric(10, 2) not null,
  unit text not null default 'stueck'
    check (unit in ('stueck', 'stunden', 'pauschal', 'tage', 'km')),
  unit_price bigint not null,
  vat_rate int not null default 19,
  total bigint not null,
  created_at timestamptz not null default now()
);

create table reminders (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references invoices(id) on delete cascade,
  reminder_number text not null unique,
  reminder_level int not null,
  reminder_date timestamptz not null,
  reminder_fee bigint not null default 0,
  new_due_date timestamptz,
  pdf_url text,
  created_at timestamptz not null default now()
);

create table invoice_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  customer_id bigint references customers(id) on delete set null,
  payment_term_days int not null default 7,
  vat_rate int not null default 19,
  is_reverse_charge boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table template_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references invoice_templates(id) on delete cascade,
  position int not null,
  description text not null,
  details text,
  quantity numeric(10, 2) not null,
  unit text not null default 'stueck'
    check (unit in ('stueck', 'stunden', 'pauschal', 'tage', 'km')),
  unit_price bigint not null,
  created_at timestamptz not null default now()
);

-- Globale Einstellungen (Key/Value) – aktive Firmen-/PDF-Stammdaten.
create table invoice_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text,
  updated_at timestamptz not null default now()
);

-- --- Indizes ---------------------------------------------------------------
create index idx_invoices_customer on invoices(customer_id);
create index idx_invoices_status on invoices(status);
create index idx_invoice_items_invoice on invoice_items(invoice_id);
create index idx_customers_company on customers(company_id);
create index idx_template_items_template on template_items(template_id);

-- --- updated_at Trigger (Funktion set_updated_at existiert bereits) ---------
create trigger trg_companies_updated_at before update on companies
  for each row execute function set_updated_at();
create trigger trg_customers_updated_at before update on customers
  for each row execute function set_updated_at();
create trigger trg_invoices_updated_at before update on invoices
  for each row execute function set_updated_at();
create trigger trg_invoice_templates_updated_at before update on invoice_templates
  for each row execute function set_updated_at();

-- --- Row Level Security (gleiches Muster: nur authenticated, sonst nichts) --
alter table companies         enable row level security;
alter table customers         enable row level security;
alter table invoices          enable row level security;
alter table invoice_items     enable row level security;
alter table reminders         enable row level security;
alter table invoice_templates enable row level security;
alter table template_items    enable row level security;
alter table invoice_settings  enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'companies', 'customers', 'invoices', 'invoice_items', 'reminders',
    'invoice_templates', 'template_items', 'invoice_settings'
  ]
  loop
    execute format(
      'create policy %I on %I for all to authenticated using (true) with check (true)',
      t || '_authenticated_all', t
    );
  end loop;
end;
$$;
